config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  get '/products', to: 'products#index'
  get '/products/:id', to: 'products#show', as: 'product'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true
  validates :price, presence: true
  validates :stock_quantity, presence: true

  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>U5</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>Products List</h1>

<table>exit
  <thead>
  <tr>
    <th>Title</th>
    <th>Price</th>
    <th>Stock Quantity</th>
  </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%= link_to product.title, product_path(product) %></td>
      <td><%= number_to_currency(product.price) %></td>
      <td><%= product.stock_quantity %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/products/show.html.erb
<h1><%= @product.title %></h1>
<p><%= @product.description %></p>
<p>Price: <%= number_to_currency(@product.price) %></p>
<p>Stock Quantity: <%= @product.stock_quantity %></p>